# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181128_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/static/img/default.png', upload_to='static/avatar/'),
        ),
    ]
